### ISSUE TITLE
[BUG] sql::InvalidInstanceException

### ISSUE THREAD

**Issue by brydon1** [mvwater/mvwater-cpp#13]
**Describe the bug**
Issue with parsing sql results

**To Reproduce**
1. Run ./TestSearchAddress
2. There will be a bunch of printed statements, starting with "About to create query" and ending
with "Beginning while loop"
3. After this you will see the error "terminate called after throwing an instance of 'sql::InvalidInstanceException"

**Special scenarios**
None.

**Expected behavior**
See "to reproduce"

**Type of termination**
Crash

**Additional context**

**Comment by kim3-sudo** [comment]
Able to replicate the issue. Looking into it now.

**Comment by brydon1** [comment]
Here is the parent of the commit during which it worked: 76c8acd

Not sure if the issue will come up again.
