### ISSUE TITLE
[BUG] After search, shows consumption history

### ISSUE THREAD

**Issue by kim3-sudo** [mvwater/mvwater-cpp#24]
**Describe the bug**
After searching by address, the search results page shows "Consumption History" instead of just the search results.

**To Reproduce**
1. Go to https://cslab.kenyon.edu/class/softdev/canfield1/Mvwater/Web_Code/search_page.html
2. Select the search type Address
3. Search for 'p'

**Special scenarios**
No special scenarios

**Expected behavior**
Consumption history should not show.

**Type of termination**
No termination.

**Additional context**
N/A

**Comment by scanf13ld** [comment]
Fixed Search.js line 102
